version: "3"

dotenv: ['.env']

tasks:
  run:
    desc: "Run Chat service"
    cmds:
      - go run cmd/chat/main.go --config=./config/local.yaml
      
  default:
    desc: "default runs the Chat service"
    cmds:
      - task: run
  
  migrate-up:
    desc: "Apply database migrations using custom Go migrator"
    cmds:
      - go run cmd/migrator/main.go -db-url="{{.MIGRATOR_DB_URL}}" -migrations-path="./migrations" -action="up"

  migrate-down:
    desc: "Rollback database migrations using custom Go migrator"
    cmds:
      - go run cmd/migrator/main.go -db-url="{{.MIGRATOR_DB_URL}}" -migrations-path="./migrations" -action="down"