// Code generated by MockGen. DO NOT EDIT.
// Source: chat.go
//
// Generated by this command:
//
//	mockgen -source=chat.go -destination=mocks/mock_chat.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "chat/internal/domain/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSSOProvider is a mock of SSOProvider interface.
type MockSSOProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSSOProviderMockRecorder
	isgomock struct{}
}

// MockSSOProviderMockRecorder is the mock recorder for MockSSOProvider.
type MockSSOProviderMockRecorder struct {
	mock *MockSSOProvider
}

// NewMockSSOProvider creates a new mock instance.
func NewMockSSOProvider(ctrl *gomock.Controller) *MockSSOProvider {
	mock := &MockSSOProvider{ctrl: ctrl}
	mock.recorder = &MockSSOProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSOProvider) EXPECT() *MockSSOProviderMockRecorder {
	return m.recorder
}

// IsUserExists mocks base method.
func (m *MockSSOProvider) IsUserExists(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserExists", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserExists indicates an expected call of IsUserExists.
func (mr *MockSSOProviderMockRecorder) IsUserExists(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserExists", reflect.TypeOf((*MockSSOProvider)(nil).IsUserExists), ctx, userID)
}

// MockChatCache is a mock of ChatCache interface.
type MockChatCache struct {
	ctrl     *gomock.Controller
	recorder *MockChatCacheMockRecorder
	isgomock struct{}
}

// MockChatCacheMockRecorder is the mock recorder for MockChatCache.
type MockChatCacheMockRecorder struct {
	mock *MockChatCache
}

// NewMockChatCache creates a new mock instance.
func NewMockChatCache(ctrl *gomock.Controller) *MockChatCache {
	mock := &MockChatCache{ctrl: ctrl}
	mock.recorder = &MockChatCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatCache) EXPECT() *MockChatCacheMockRecorder {
	return m.recorder
}

// CheckChatMember mocks base method.
func (m *MockChatCache) CheckChatMember(ctx context.Context, chatID, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckChatMember", ctx, chatID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckChatMember indicates an expected call of CheckChatMember.
func (mr *MockChatCacheMockRecorder) CheckChatMember(ctx, chatID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckChatMember", reflect.TypeOf((*MockChatCache)(nil).CheckChatMember), ctx, chatID, userID)
}

// SetChatMember mocks base method.
func (m *MockChatCache) SetChatMember(ctx context.Context, chatID, userID int64, isMember bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetChatMember", ctx, chatID, userID, isMember)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetChatMember indicates an expected call of SetChatMember.
func (mr *MockChatCacheMockRecorder) SetChatMember(ctx, chatID, userID, isMember any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetChatMember", reflect.TypeOf((*MockChatCache)(nil).SetChatMember), ctx, chatID, userID, isMember)
}

// MockChatSaver is a mock of ChatSaver interface.
type MockChatSaver struct {
	ctrl     *gomock.Controller
	recorder *MockChatSaverMockRecorder
	isgomock struct{}
}

// MockChatSaverMockRecorder is the mock recorder for MockChatSaver.
type MockChatSaverMockRecorder struct {
	mock *MockChatSaver
}

// NewMockChatSaver creates a new mock instance.
func NewMockChatSaver(ctrl *gomock.Controller) *MockChatSaver {
	mock := &MockChatSaver{ctrl: ctrl}
	mock.recorder = &MockChatSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatSaver) EXPECT() *MockChatSaverMockRecorder {
	return m.recorder
}

// CreateChat mocks base method.
func (m *MockChatSaver) CreateChat(ctx context.Context, members []int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChat", ctx, members)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChat indicates an expected call of CreateChat.
func (mr *MockChatSaverMockRecorder) CreateChat(ctx, members any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChat", reflect.TypeOf((*MockChatSaver)(nil).CreateChat), ctx, members)
}

// DeleteChat mocks base method.
func (m *MockChatSaver) DeleteChat(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChat", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChat indicates an expected call of DeleteChat.
func (mr *MockChatSaverMockRecorder) DeleteChat(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChat", reflect.TypeOf((*MockChatSaver)(nil).DeleteChat), ctx, chatID)
}

// MockChatProvider is a mock of ChatProvider interface.
type MockChatProvider struct {
	ctrl     *gomock.Controller
	recorder *MockChatProviderMockRecorder
	isgomock struct{}
}

// MockChatProviderMockRecorder is the mock recorder for MockChatProvider.
type MockChatProviderMockRecorder struct {
	mock *MockChatProvider
}

// NewMockChatProvider creates a new mock instance.
func NewMockChatProvider(ctrl *gomock.Controller) *MockChatProvider {
	mock := &MockChatProvider{ctrl: ctrl}
	mock.recorder = &MockChatProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatProvider) EXPECT() *MockChatProviderMockRecorder {
	return m.recorder
}

// ChatExists mocks base method.
func (m *MockChatProvider) ChatExists(ctx context.Context, chatID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatExists", ctx, chatID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatExists indicates an expected call of ChatExists.
func (mr *MockChatProviderMockRecorder) ChatExists(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatExists", reflect.TypeOf((*MockChatProvider)(nil).ChatExists), ctx, chatID)
}

// IsChatMember mocks base method.
func (m *MockChatProvider) IsChatMember(ctx context.Context, chatID, requestorID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsChatMember", ctx, chatID, requestorID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsChatMember indicates an expected call of IsChatMember.
func (mr *MockChatProviderMockRecorder) IsChatMember(ctx, chatID, requestorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsChatMember", reflect.TypeOf((*MockChatProvider)(nil).IsChatMember), ctx, chatID, requestorID)
}

// MockMessageSaver is a mock of MessageSaver interface.
type MockMessageSaver struct {
	ctrl     *gomock.Controller
	recorder *MockMessageSaverMockRecorder
	isgomock struct{}
}

// MockMessageSaverMockRecorder is the mock recorder for MockMessageSaver.
type MockMessageSaverMockRecorder struct {
	mock *MockMessageSaver
}

// NewMockMessageSaver creates a new mock instance.
func NewMockMessageSaver(ctrl *gomock.Controller) *MockMessageSaver {
	mock := &MockMessageSaver{ctrl: ctrl}
	mock.recorder = &MockMessageSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageSaver) EXPECT() *MockMessageSaverMockRecorder {
	return m.recorder
}

// DeleteMessage mocks base method.
func (m *MockMessageSaver) DeleteMessage(ctx context.Context, msgID, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, msgID, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockMessageSaverMockRecorder) DeleteMessage(ctx, msgID, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockMessageSaver)(nil).DeleteMessage), ctx, msgID, chatID)
}

// SaveMessage mocks base method.
func (m *MockMessageSaver) SaveMessage(ctx context.Context, chatID, senderID int64, text string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, chatID, senderID, text)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockMessageSaverMockRecorder) SaveMessage(ctx, chatID, senderID, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockMessageSaver)(nil).SaveMessage), ctx, chatID, senderID, text)
}

// MockMessageProvider is a mock of MessageProvider interface.
type MockMessageProvider struct {
	ctrl     *gomock.Controller
	recorder *MockMessageProviderMockRecorder
	isgomock struct{}
}

// MockMessageProviderMockRecorder is the mock recorder for MockMessageProvider.
type MockMessageProviderMockRecorder struct {
	mock *MockMessageProvider
}

// NewMockMessageProvider creates a new mock instance.
func NewMockMessageProvider(ctrl *gomock.Controller) *MockMessageProvider {
	mock := &MockMessageProvider{ctrl: ctrl}
	mock.recorder = &MockMessageProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageProvider) EXPECT() *MockMessageProviderMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockMessageProvider) GetHistory(ctx context.Context, chatID, limit, offset int64) ([]models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, chatID, limit, offset)
	ret0, _ := ret[0].([]models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockMessageProviderMockRecorder) GetHistory(ctx, chatID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockMessageProvider)(nil).GetHistory), ctx, chatID, limit, offset)
}

// GetMessage mocks base method.
func (m *MockMessageProvider) GetMessage(ctx context.Context, chatID, msgID int64) (models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, chatID, msgID)
	ret0, _ := ret[0].(models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockMessageProviderMockRecorder) GetMessage(ctx, chatID, msgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockMessageProvider)(nil).GetMessage), ctx, chatID, msgID)
}
